SpotifyUserFollowers:
  type: object
  config:
    name: SpotifyUserFollowers
    description: 'Represent the followers of the user'
    fields:
      href:
        type: 'String'
      total:
        type: 'Int!'
