SpotifyPaginatedList:
  type: object
  config:
    name: SpotifyPaginatedList
    description: 'A paginated list from the Spotify API'
    fields:
      href:
        type: 'String!'
      items:
        type: '[PaginatedItem!]!'
      limit:
        type: 'Int!'
      offset:
        type: 'Int!'
      total:
        type: 'Int!'
      next:
        type: 'String'
      previous:
        type: 'String'
