SpotifyUser:
  type: object
  config:
    name: SpotifyUser
    description: 'A user from the Spotify API'
    fields:
      id:
        type: 'ID!'
      plan:
        type: 'SpotifyUserPlan!'
      followers:
        type: 'SpotifyUserFollowers!'
      displayName:
        type: 'String!'
      images:
        type: '[SpotifyUserImage!]!'
      birthdate:
        type: 'DateTime!'
      email:
        type: 'String!'
      href:
        type: 'String'
      playlists:
        type: 'SpotifyPaginatedList!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\SpotifyUser\\SpotifyUserPlaylistsResolver", [value, args])'
        args:
          limit:
            type: 'Int'
            defaultValue: 20
          offset:
            type: 'Int'
            defaultValue: 0
      player:
        type: 'SpotifyUserPlayer!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\SpotifyUser\\SpotifyUserPlayerResolver", [value])'
