SpotifyUserPlayer:
  type: object
  config:
    name: SpotifyUserPlayer
    fields:
      id:
        builder: "Relay::GlobalId"
        builderConfig:
          typeName: SpotifyUserPlayer
      device:
        type: 'SpotifyUserPlayerDevice!'
        description: 'Get the current playing device of the user'
      shuffling:
        type: 'Boolean!'
      repeat:
        type: 'SpotifyUserRepeatMode!'
      timestamp:
        type: 'Int!'
      progression:
        type: 'String!'
        resolve: '@=resolver("App\\GraphQL\\Resolver\\SpotifyUser\\SpotifyUserPlayerProgressionResolver", [value, args])'
        args:
          format:
            type: 'ProgressionUnit'
            defaultValue: '@=constant("App\\Enum\\ProgressionUnit::MINUTES_SECONDS")'
      playing:
        type: 'Boolean!'
