ToggleUserPlayerPlaybackPayload:
  type: relay-mutation-payload
  config:
    description: 'Payload of toggleUserPlayerPlayback mutation'
    fields:
      player:
        type: 'SpotifyUserPlayer!'
        description: 'The newly modified player instance'
